<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vinays-MacBook-Pro.local" name="com.phunware.m3.api.tests.Attributes_old" tests="7" failures="1" timestamp="25 Apr 2017 03:41:10 GMT" time="6.503" errors="0">
  <testcase name="postOneAttribute" time="0.477" classname="com.phunware.m3.api.tests.Attributes_old">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &quot;Duplicate entry&quot;
     but: was &quot;requirement failed: attribute with the name provided already exists&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "Duplicate entry"
     but: was "requirement failed: attribute with the name provided already exists"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.phunware.m3.api.tests.Attributes_old.postOneAttribute(Attributes.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
]]>
    </failure>
  </testcase> <!-- postOneAttribute -->
  <testcase name="getOneAttribute" time="2.929" classname="com.phunware.m3.api.tests.Attributes_old"/>
  <testcase name="addMultipleValuesToAttribute" time="0.258" classname="com.phunware.m3.api.tests.Attributes_old"/>
  <testcase name="addOneValueToAttribute" time="0.524" classname="com.phunware.m3.api.tests.Attributes_old"/>
  <testcase name="getAllAttributes" time="1.311" classname="com.phunware.m3.api.tests.Attributes_old"/>
  <testcase name="enableOneAttribute" time="0.531" classname="com.phunware.m3.api.tests.Attributes_old"/>
  <testcase name="disableOneAttribute" time="0.473" classname="com.phunware.m3.api.tests.Attributes_old"/>
</testsuite> <!-- com.phunware.m3.api.tests.Attributes_old -->
